### ISSUE TITLE
특정 키워드에 자동 반응 하는 기능의 설정 추가

### ISSUE THREAD

**Issue by miraclehoshi** [LunaNyan/Luna_Libertin_Discord_Bot#2]
https://i.postimg.cc/Hn9rdB90/examp.png

으악 하면 봇이 으악 하는
호출 없는데 봇이 키워드 감지해서 나오는거
끄는 옵션 추가해주세용

**Comment by LunaNyan** [comment]
서버 관리자이신 경우 "루냥아 일상대화 접두어"로 토글할 수 있습니다.
